# Generated by Django 3.2.9 on 2021-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(help_text='максимум 20 символов', max_length=20, verbose_name='Имя'),
        ),
    ]
